# Generated by Django 4.2 on 2023-04-13 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnkiCard",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("word", models.CharField(max_length=64)),
                ("translation", models.CharField(max_length=64)),
                ("image", models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("difficulty", models.IntegerField()),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lang_app.topic"
                    ),
                ),
            ],
        ),
    ]
