# Generated by Django 4.2 on 2023-04-13 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lang_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(name="ankicard", table="anki_card",),
    ]
