# Generated by Django 4.2 on 2023-04-13 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lang_app", "0002_alter_ankicard_table"),
    ]

    operations = [
        migrations.AlterModelTable(name="lesson", table="lesson",),
        migrations.AlterModelTable(name="topic", table="topic",),
    ]
