# Generated by Django 4.2 on 2023-04-15 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lang_app", "0003_alter_lesson_table_alter_topic_table"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lesson", old_name="difficulty", new_name="grade",
        ),
    ]
